Repository ironcore-dev/dpservice, pull requests merged in 2023-12, with the labels that each got.

#449 Shebang needs to be the first line in the file. Fix in dp_service.py
  test/dp_service.py
Labels: bug, size/XS

#453 Add SPDX to generated source/header files
  .reuse/dep5
  docs/deployment/help_dpservice-dump.md
  hack/dp_conf_generate.py
  include/dp_conf_opts.h
  src/dp_conf_opts.c
  tools/dump/opts.c
  tools/dump/opts.h
Labels: documentation, enhancement, size/S

#458 Add `CODEOWNERS` to project
  CODEOWNERS
Labels: chore, size/XS
