Repository ironcore-dev/dpservice, pull requests merged in 2024-01, with the labels that each got.

#465 Add missing licence text to dp_icmpv6.h
  include/protocols/dp_icmpv6.h
Labels: bug, size/XS

#469 Do not pad dhcp6 packets and options
  include/protocols/dp_dhcpv6.h
Labels: bug, size/S

#471 Handle both v4 and v6 traffic in firewall node
  src/nodes/firewall_node.c
Labels: bug, size/XS

#472 Rename the lb ipv6 test case so that it is not shadowed
  test/test_lb.py
Labels: bug, size/XS

#474 Modify dataplane drawing to reflect ipv6 changes
  docs/sys_design/dpservice_dataplane.drawio.png
  src/nodes/conntrack_node.c
Labels: enhancement, size/XS

#484 Improve ipv6 firewall implementation and the tests
  src/dp_firewall.c
  test/grpc_client.py
  test/test_lb.py
  test/test_pf_to_vf.py
  test/test_vf_to_pf.py
  test/test_vf_to_vf.py
Labels: enhancement, size/M

#486 Telemetry test should check for a pattern of string
  test/test_telemetry.py
Labels: enhancement, size/XS
