Repository ironcore-dev/dpservice, pull requests merged in 2024-02, with the labels that each got.

#485 Introduce a new NIC type Bluefield2
  .github/workflows/publish-docker.yml
  docs/deployment/help_dpservice-bin.md
  hack/dp_conf.json
  include/dp_conf_opts.h
  src/dp_conf_opts.c
  src/dp_port.c
  src/dp_util.c
Labels: documentation, enhancement, size/S

#488 Ignore sysfs error for metering config due to unknow linux 6.x issue
  include/dp_util.h
  src/dp_port.c
  src/dp_util.c
Labels: bug, size/S

#492 Introduce a manual trigger for PR triggered arm64 builds
  .github/workflows/publish-docker.yml
Labels: enhancement, size/S

#493 Do not add empty IP address of an interface to the route table
  src/grpc/dp_async_grpc.cpp
  src/grpc/dp_grpc_impl.c
  test/test_zzz_grpc.py
Labels: bug, size/S

#494 Adjust prepare.sh script to support Bluefield 2
  hack/prepare.sh
Labels: enhancement, size/S

#500 Update prepare.sh to work with newer Linux kernel
  hack/prepare.sh
Labels: bug, size/XS

#503 Add bluefield identifier MT_0000000541 to the prepare.sh list
  hack/prepare.sh
Labels: bug, size/XS
