Repository ironcore-dev/dpservice, pull requests merged in 2024-06, with the labels that each got.

#567 Create a script to read current version from git, fixes #566
  cli/dpservice-cli/Makefile
  cli/dpservice-exporter/Makefile
  go/dpservice-go/hack/generate-proto.sh
  hack/get_version.sh
  include/meson.build
  meson.build
Labels: bug, size/S

#569 Move dp_grpc_client into cli/ subdirectory
  cli/dp_grpc_client/dp_grpc_client.cpp
  cli/dp_grpc_client/meson.build
  cli/meson.build
  test/dp_grpc_client.py
  tools/meson.build
Labels: enhancement, size/S

#570 Proper fix for version.h generation
  include/meson.build
  src/meson.build
  tools/dump/meson.build
Labels: bug, size/S

#575 Change gRPC request input error to a warning
  src/dp_nat.c
Labels: bug, size/XS

#577 Reorganize licence files and delete unnecessary ones
  .reuse/dep5
  README.md
  cli/dpservice-cli/CODEOWNERS
  cli/dpservice-cli/LICENSE
  cli/dpservice-cli/LICENSES/Apache-2.0.txt
  cli/dpservice-exporter/LICENSE
  cli/dpservice-exporter/LICENSES/Apache-2.0.txt
  go/dpservice-go/CODEOWNERS
  go/dpservice-go/LICENSE
  go/dpservice-go/LICENSES/Apache-2.0.txt
Labels: bug, documentation, size/XL

#578 Add missing licence info to exporter.py
  test/exporter.py
Labels: bug, size/XS

#582 Move local tests to a separate directory
  .gitignore
  Dockerfile
  test/local/config.py
  test/local/conftest.py
  test/local/dp_grpc_client.py
  test/local/dp_service.py
  test/local/exporter.py
  test/local/gdbinit
  test/local/grpc_client.py
  test/local/helpers.py
  test/local/runtest.py
  test/local/tcp_tester.py
  test/local/test_arp.py
  test/local/test_dhcpv4.py
  test/local/test_dhcpv6.py
  test/local/test_encap.py
  test/local/test_flows.py
  test/local/test_ipv6_nd.py
  test/local/test_lb.py
  test/local/test_nat.py
  test/local/test_pf_to_vf.py
  test/local/test_telemetry.py
  test/local/test_vf_to_pf.py
  test/local/test_vf_to_vf.py
  test/local/test_virtsvc.py
  test/local/test_vni.py
  test/local/test_zzz_grpc.py
  test/local/xtratest_flow_timeout.py
Labels: enhancement, size/S

#585 Update documentation after repository merge
  docs/development/building.md
  docs/development/mellanox.md
  docs/development/running.md
  docs/testing/README.md
  hack/prepare.sh
  include/dp_log.h
  src/dp_util.c
Labels: documentation, enhancement, size/S
