Repository ironcore-dev/dpservice, pull requests merged in 2024-07, with the labels that each got.

#586 Do not run/fail gRPC GetInit test when attaching to a running service
  test/local/test_zzz_grpc.py
Labels: bug, size/XS

#587 Place iface_id as the first element in the struct for correct alignment on ARM
  include/grpc/dp_grpc_api.h
Labels: bug, size/S

#596 Add Grafana dashboard template
  cli/dpservice-exporter/README.md
  cli/dpservice-exporter/dashboard/grafana.json
Labels: documentation, enhancement, size/XXL
