Repository ironcore-dev/dpservice, pull requests merged in 2024-05, with the labels that each got.

#555 Fix version template to re-generate during build instead of configure phase
  include/meson.build
Labels: bug, size/S

#558 Update of Go dependencies
  cli/dpservice-cli/go.mod
  cli/dpservice-cli/go.sum
  go/dpservice-go/go.mod
  go/dpservice-go/go.sum
Labels: size/M, dependencies

#544 Added port range check when adding neighnat entry
  include/dp_nat.h
  src/dp_nat.c
Labels: bug, size/S

#561 Remove 'Build and Publish Docker Image' from PR actions
  .github/workflows/publish-docker.yml
Labels: enhancement, size/S
