Repository ironcore-dev/dpservice, pull requests merged in 2024-04, with the labels that each got.

#516 Use "--rm" for the docker tester image execution to clean up
  .github/workflows/publish-docker-tester.yml
Labels: bug, size/XS

#510 Update documentation to reflect DPDK 23.11 change
  docs/README.md
  docs/development/building.md
Labels: bug, documentation, size/S

#511 Remove duplicate rte_flow macro
  include/rte_flow/dp_rte_flow_helpers.h
  src/rte_flow/dp_rte_flow_capture.c
  src/rte_flow/dp_rte_flow_init.c
Labels: bug, documentation, size/S

#519 Fix packed structure being used for nat portmap hash key
  include/dp_nat.h
  src/dp_nat.c
  test/test_flows.py
Labels: bug, size/S

#523 Fix for running automation test on the tester machine
  test/dp_service.py
Labels: bug, size/XS

#530 Simplify grpc route creation/deletion code
  include/dp_lpm.h
  src/dp_lpm.c
  src/grpc/dp_grpc_impl.c
Labels: enhancement, size/M

#533 Change LB algorithm test based on encountered production issue
  Dockerfile
  test/lb_tester.py
  test/test_lb.py
  test/xtratest_flow_timeout.py
Labels: enhancement, size/L

#535 Finish IP structure refactoring after Maglev integration.
  src/dp_lb.c
Labels: enhancement, size/XS

#537 Remove flows for a loadbalancer target on deletion
  include/dp_flow.h
  include/dp_ipaddr.h
  src/dp_flow.c
  src/grpc/dp_grpc_impl.c
  test/xtratest_flow_timeout.py
Labels: bug, size/M
