Repository ironcore-dev/dpservice, pull requests merged in 2025-06, with the labels that each got.

#684 Add missing zmalloc check
  src/dp_nat.c
Labels: bug, size/S

#682 Remove pytest packet noise, fix HW test side-effects
  test/local/helpers.py
Labels: bug, size/XS

#689 Add one tool for VM used in benchmarktest
  test/benchmark_test/config_templates/provision_tmpl.ign
Labels: bug, size/XS

#685 Add missing frees in argument parsing
  src/dp_conf.c
  src/dp_service.c
Labels: bug, size/S

#690 Provide option to bind VFs to vfio driver
  hack/prepare.sh
Labels: size/M

#694 Fix REUSE
  REUSE.toml
Labels: bug, size/S
